name: Release
on:
  release:
    types: [created]

jobs:
  release:
    name: release ubuntu
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose --release --target-dir ./out

    - uses: actions/github-script@v7.0.1
      with:
        script: gh release upload $GITHUB_REF ./out/release/timetracker
